### ISSUE TITLE
inputPercentage vacío quiebra el programa

### ISSUE THREAD

**Issue by tzohpilotl** [UG-Mobile2016/TipCalc#1]
No sé si les pase lo mismo pero ni `if (strInputTipPercentage.isEmpty())`, ni `if("".equals(strInputTipPercentage)` arroja `true` a pesar que el debugger muestra que, efectivamente, `strInputTipPercentage = ""`. Entonces, cuando quiero convertir el string, que supuestamente no está vacío, a entero, surge un error porque no se puede parsear la cadena "".

**Comment by JuanCrg90** [comment]
¿Al final como lo resolviste?
