### ISSUE TITLE
Comportamiento extraño en la recyclerview

### ISSUE THREAD

**Issue by tzohpilotl** [UG-Mobile2016/TipCalc#2]
¿Han notado que los registros de cálculo pasados "desaparecen" cuando el teclado se cierra? Supongo que el layout se expande, dejando mucho espacio entre líneas. Cuando el teclado aparece, el layout se encoje y los ítems se ven más cerca unos de otros. ¿Alguien sabe cómo evitar que se separen tanto cuando se cierra el teclado?

**Comment by JuanCrg90** [comment]
¿Lograste resolver tu problema?
